### ISSUE TITLE
Board seem to be running at 64Mhz not 80Mhz

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [stm32duino/Arduino_Core_STM32L4#1]
PLL multiplier settings seem to be for the board to run at 64Mhz not the 80MHz as advertised on STM's website.

Looking in hw_config.c there are 2 possible speeds, controlled by a definition of ENABLE_HIGH_SPEED

However if the code is recompiled with ENABLE_HIGH_SPEED defined, the board seems to run even slower

**Comment by LMESTM** [comment]
@rogerclarkmelbourne  : may we close this issue ?

**Comment by rogerclarkmelbourne** [comment]
Laurent.
Yes. If its fixed, please close it.
