### ISSUE TITLE
I2C pins are hard coded in the core

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [stm32duino/Arduino_Core_STM32L4#12]
This is the same issue as in the F1 code.

I2C pins are hard coded in the core.
https://github.com/stm32duino/Arduino_Core_STM32L4/blob/master/system/libstm32l4/source/twi.c#L169-L180

Pins need to be different for each variant.

This has been discussed by @danieleff and myself, and we think easiest solution is to use #define for the pins, as it is difficult to change the twi code to move the whole init function to on of the files in the variant folder

**Comment by fpistm** [comment]
This issue is corrected on new repo which support STM32F4:
[](https://github.com/stm32duino/Arduino_Core_STM32)
