### ISSUE TITLE
PWM pins are not set in AF mode again

### ISSUE THREAD

**Issue by jmchiappa** [stm32duino/Arduino_Core_STM32L4#14]
Work on NUCLEO_L476RG

How to reproduce the issue
start with D3 as PWM, works fine
change D3 as output
set back D3 as PWM, PWM doesn't work anymore.

Issues : GPIOB_3 isn't set as AF mode in 0x48000400 MODE15[1:0]= 01 instead of 10

you should add in analog.c ,line #708:
    `HAL_TIM_PWM_MspInit(&g_analog_config[id].timHandle);`

after that it works fine

**Comment by fpistm** [comment]
Hi @jmchiappa ,
This issue is now corrected (I've tested your use case) on this new repo:
[](https://github.com/stm32duino/Arduino_Core_STM32)
Which support the NUCLEO_L476RG.
This one is deprecated.
