### ISSUE TITLE
Class inconsistencies in the Serial mappings

### ISSUE THREAD

**Issue by edogaldo** [stm32duino/Arduino_Core_STM32L4#15]
In variants/STM32L476RG_Nucleo/variant.cpp:
```
UARTClass Serial(USART2_E);    //available on PA2/PA3
UARTClass Serial1(USART1_E);   //available on PA9/PA10
USARTClass Serial2(USART2_E);  //available on PA2/PA3
USARTClass Serial3(UART4_E);   //available on PA0/PA1
```
Why using UARTClass for Serial and Serial1?
Why using USARTClass for Serial3?

**Comment by ghost** [comment]
You right this is inconsistent but there is no difference to use UART or USART class with Nucleo board.

**Comment by fpistm** [comment]
Hi @edogaldo ,
U(S)ART class has been reworked in new repo:
[](https://github.com/stm32duino/Arduino_Core_STM32)
It is now consistent.
