### ISSUE TITLE
Winterrupts.c writes but never reads .configured

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [stm32duino/Arduino_Core_STM32L4#4]
In various lines Winterrupts.c e.g. 

https://github.com/stm32duino/Arduino_Core_STM32L4/blob/master/cores/arduino/WInterrupts.c#L43

.configured is written but never read.

These lines can be removed and 

`PinDescription g_intPinConfigured[MAX_DIGITAL_IOS];`

can be changed to a array of pointers to PinDescription 

(and the code changed accordingly)

**Comment by ghost** [comment]
g_intPinConfigured can be changed to a pointer. 

I think the parameter "configured" is not well used in the entire code. I don't know if this parameter is really useful. For the moment we keep it.

**Comment by rogerclarkmelbourne** [comment]
We have made a lot of changes to the F1 which probably include changes to this.

The complicated pin mapping function have been simplified etc

Ideally the code for the different MCU series would not differ too much, and perhaps the L4 code should be updated to be more like the revised F1 code.

**Comment by fpistm** [comment]
This issue was moved to stm32duino/Arduino_Core_STM32#6
