### ISSUE TITLE
Most of the g_analog_config does not need to be in RAM

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [stm32duino/Arduino_Core_STM32L4#5]
Only the  `.dacInstance` and `.timInstance` members of g_analog_config need to be in RAM

https://github.com/stm32duino/Arduino_Core_STM32L4/blob/master/system/libstm32l4/source/analog.c#L95

The rest of the struct is const. Hence these 2 members should be in their own separate arrays
g_analog_config should be declared as const
Code should be modified accordingly to match these changes

**Comment by ghost** [comment]
We are looking for an alternative to this structure (less code usage and more flexible to integrate variant board).

**Comment by rogerclarkmelbourne** [comment]
We have already made changes to the F1 repo to fix this, but I don't know if those changes would be applicable to the L4. 
Its not so much of an issue on the L4 because it has a lot of RAM, but ideally the implementation of this would not differ very much between each MCU series

**Comment by fpistm** [comment]
No more applicable on new repo:
[](https://github.com/stm32duino/Arduino_Core_STM32)
